// Country data for Flag Quiz application
// This file contains all country information used by both learning and quiz modes
// Based on ISO 3166-1-alpha-2 country codes supported by flag-icons library

const CountryData = {
    'eu': [
        { code: 'ad', name: 'Andorra', capital: 'Andorra la Vella', currency: 'EUR' },
        { code: 'al', name: 'Albania', capital: 'Tirana', currency: 'ALL' },
        { code: 'am', name: 'Armenia', capital: 'Yerevan', currency: 'AMD' },
        { code: 'at', name: 'Austria', capital: 'Vienna', currency: 'EUR' },
        { code: 'az', name: 'Azerbaijan', capital: 'Baku', currency: 'AZN' },
        { code: 'ba', name: 'Bosnia and Herzegovina', capital: 'Sarajevo', currency: 'BAM' },
        { code: 'be', name: 'Belgium', capital: 'Brussels', currency: 'EUR' },
        { code: 'bg', name: 'Bulgaria', capital: 'Sofia', currency: 'BGN' },
        { code: 'by', name: 'Belarus', capital: 'Minsk', currency: 'BYN' },
        { code: 'ch', name: 'Switzerland', capital: 'Bern', currency: 'CHF' },
        { code: 'cy', name: 'Cyprus', capital: 'Nicosia', currency: 'EUR' },
        { code: 'cz', name: 'Czech Republic', capital: 'Prague', currency: 'CZK' },
        { code: 'de', name: 'Germany', capital: 'Berlin', currency: 'EUR' },
        { code: 'dk', name: 'Denmark', capital: 'Copenhagen', currency: 'DKK' },
        { code: 'ee', name: 'Estonia', capital: 'Tallinn', currency: 'EUR' },
        { code: 'es', name: 'Spain', capital: 'Madrid', currency: 'EUR' },
        { code: 'fi', name: 'Finland', capital: 'Helsinki', currency: 'EUR' },
        { code: 'fo', name: 'Faroe Islands', capital: 'Tórshavn', currency: 'DKK' },
        { code: 'fr', name: 'France', capital: 'Paris', currency: 'EUR' },
        { code: 'gb', name: 'United Kingdom', capital: 'London', currency: 'GBP' },
        { code: 'ge', name: 'Georgia', capital: 'Tbilisi', currency: 'GEL' },
        { code: 'gg', name: 'Guernsey', capital: 'St. Peter Port', currency: 'GBP' },
        { code: 'gi', name: 'Gibraltar', capital: 'Gibraltar', currency: 'GIP' },
        { code: 'gl', name: 'Greenland', capital: 'Nuuk', currency: 'DKK' },
        { code: 'gr', name: 'Greece', capital: 'Athens', currency: 'EUR' },
        { code: 'hr', name: 'Croatia', capital: 'Zagreb', currency: 'EUR' },
        { code: 'hu', name: 'Hungary', capital: 'Budapest', currency: 'HUF' },
        { code: 'ie', name: 'Ireland', capital: 'Dublin', currency: 'EUR' },
        { code: 'im', name: 'Isle of Man', capital: 'Douglas', currency: 'GBP' },
        { code: 'is', name: 'Iceland', capital: 'Reykjavik', currency: 'ISK' },
        { code: 'it', name: 'Italy', capital: 'Rome', currency: 'EUR' },
        { code: 'je', name: 'Jersey', capital: 'Saint Helier', currency: 'GBP' },
        { code: 'li', name: 'Liechtenstein', capital: 'Vaduz', currency: 'CHF' },
        { code: 'lt', name: 'Lithuania', capital: 'Vilnius', currency: 'EUR' },
        { code: 'lu', name: 'Luxembourg', capital: 'Luxembourg City', currency: 'EUR' },
        { code: 'lv', name: 'Latvia', capital: 'Riga', currency: 'EUR' },
        { code: 'mc', name: 'Monaco', capital: 'Monaco', currency: 'EUR' },
        { code: 'md', name: 'Moldova', capital: 'Chișinău', currency: 'MDL' },
        { code: 'me', name: 'Montenegro', capital: 'Podgorica', currency: 'EUR' },
        { code: 'mk', name: 'North Macedonia', capital: 'Skopje', currency: 'MKD' },
        { code: 'mt', name: 'Malta', capital: 'Valletta', currency: 'EUR' },
        { code: 'nl', name: 'Netherlands', capital: 'Amsterdam', currency: 'EUR' },
        { code: 'no', name: 'Norway', capital: 'Oslo', currency: 'NOK' },
        { code: 'pl', name: 'Poland', capital: 'Warsaw', currency: 'PLN' },
        { code: 'pt', name: 'Portugal', capital: 'Lisbon', currency: 'EUR' },
        { code: 'ro', name: 'Romania', capital: 'Bucharest', currency: 'RON' },
        { code: 'rs', name: 'Serbia', capital: 'Belgrade', currency: 'RSD' },
        { code: 'ru', name: 'Russia', capital: 'Moscow', currency: 'RUB' },
        { code: 'se', name: 'Sweden', capital: 'Stockholm', currency: 'SEK' },
        { code: 'si', name: 'Slovenia', capital: 'Ljubljana', currency: 'EUR' },
        { code: 'sj', name: 'Svalbard and Jan Mayen', capital: 'Longyearbyen', currency: 'NOK' },
        { code: 'sk', name: 'Slovakia', capital: 'Bratislava', currency: 'EUR' },
        { code: 'sm', name: 'San Marino', capital: 'San Marino', currency: 'EUR' },
        { code: 'tr', name: 'Türkiye', capital: 'Ankara', currency: 'TRY' },
        { code: 'ua', name: 'Ukraine', capital: 'Kyiv', currency: 'UAH' },
        { code: 'va', name: 'Holy See', capital: 'Vatican City', currency: 'EUR' },
        { code: 'xk', name: 'Kosovo', capital: 'Pristina', currency: 'EUR' }
    ],
    'na': [
        { code: 'ag', name: 'Antigua and Barbuda', capital: 'Saint John\'s', currency: 'XCD' },
        { code: 'ai', name: 'Anguilla', capital: 'The Valley', currency: 'XCD' },
        { code: 'aw', name: 'Aruba', capital: 'Oranjestad', currency: 'AWG' },
        { code: 'bb', name: 'Barbados', capital: 'Bridgetown', currency: 'BBD' },
        { code: 'bl', name: 'Saint Barthélemy', capital: 'Gustavia', currency: 'EUR' },
        { code: 'bm', name: 'Bermuda', capital: 'Hamilton', currency: 'BMD' },
        { code: 'bq', name: 'Bonaire, Sint Eustatius and Saba', capital: 'Kralendijk', currency: 'USD' },
        { code: 'bs', name: 'Bahamas', capital: 'Nassau', currency: 'BSD' },
        { code: 'bz', name: 'Belize', capital: 'Belmopan', currency: 'BZD' },
        { code: 'ca', name: 'Canada', capital: 'Ottawa', currency: 'CAD' },
        { code: 'cr', name: 'Costa Rica', capital: 'San José', currency: 'CRC' },
        { code: 'cu', name: 'Cuba', capital: 'Havana', currency: 'CUP' },
        { code: 'cw', name: 'Curaçao', capital: 'Willemstad', currency: 'ANG' },
        { code: 'dm', name: 'Dominica', capital: 'Roseau', currency: 'XCD' },
        { code: 'do', name: 'Dominican Republic', capital: 'Santo Domingo', currency: 'DOP' },
        { code: 'gd', name: 'Grenada', capital: 'St. George\'s', currency: 'XCD' },
        { code: 'gl', name: 'Greenland', capital: 'Nuuk', currency: 'DKK' },
        { code: 'gp', name: 'Guadeloupe', capital: 'Basse-Terre', currency: 'EUR' },
        { code: 'gt', name: 'Guatemala', capital: 'Guatemala City', currency: 'GTQ' },
        { code: 'hn', name: 'Honduras', capital: 'Tegucigalpa', currency: 'HNL' },
        { code: 'ht', name: 'Haiti', capital: 'Port-au-Prince', currency: 'HTG' },
        { code: 'jm', name: 'Jamaica', capital: 'Kingston', currency: 'JMD' },
        { code: 'kn', name: 'Saint Kitts and Nevis', capital: 'Basseterre', currency: 'XCD' },
        { code: 'ky', name: 'Cayman Islands', capital: 'George Town', currency: 'KYD' },
        { code: 'lc', name: 'Saint Lucia', capital: 'Castries', currency: 'XCD' },
        { code: 'mf', name: 'Saint Martin', capital: 'Marigot', currency: 'EUR' },
        { code: 'mq', name: 'Martinique', capital: 'Fort-de-France', currency: 'EUR' },
        { code: 'ms', name: 'Montserrat', capital: 'Plymouth', currency: 'XCD' },
        { code: 'mx', name: 'Mexico', capital: 'Mexico City', currency: 'MXN' },
        { code: 'ni', name: 'Nicaragua', capital: 'Managua', currency: 'NIO' },
        { code: 'pa', name: 'Panama', capital: 'Panama City', currency: 'USD' },
        { code: 'pm', name: 'Saint Pierre and Miquelon', capital: 'Saint-Pierre', currency: 'EUR' },
        { code: 'pr', name: 'Puerto Rico', capital: 'San Juan', currency: 'USD' },
        { code: 'sv', name: 'El Salvador', capital: 'San Salvador', currency: 'USD' },
        { code: 'sx', name: 'Sint Maarten', capital: 'Philipsburg', currency: 'ANG' },
        { code: 'tc', name: 'Turks and Caicos Islands', capital: 'Cockburn Town', currency: 'USD' },
        { code: 'tt', name: 'Trinidad and Tobago', capital: 'Port of Spain', currency: 'TTD' },
        { code: 'us', name: 'United States of America', capital: 'Washington D.C.', currency: 'USD' },
        { code: 'vc', name: 'Saint Vincent and the Grenadines', capital: 'Kingstown', currency: 'XCD' },
        { code: 'vg', name: 'Virgin Islands (British)', capital: 'Road Town', currency: 'USD' },
        { code: 'vi', name: 'Virgin Islands (U.S.)', capital: 'Charlotte Amalie', currency: 'USD' }
    ],
    'sa': [
        { code: 'ar', name: 'Argentina', capital: 'Buenos Aires', currency: 'ARS' },
        { code: 'bo', name: 'Bolivia', capital: 'Sucre', currency: 'BOB' },
        { code: 'br', name: 'Brazil', capital: 'Brasília', currency: 'BRL' },
        { code: 'cl', name: 'Chile', capital: 'Santiago', currency: 'CLP' },
        { code: 'co', name: 'Colombia', capital: 'Bogotá', currency: 'COP' },
        { code: 'ec', name: 'Ecuador', capital: 'Quito', currency: 'USD' },
        { code: 'fk', name: 'Falkland Islands', capital: 'Stanley', currency: 'FKP' },
        { code: 'gf', name: 'French Guiana', capital: 'Cayenne', currency: 'EUR' },
        { code: 'gs', name: 'South Georgia and the South Sandwich Islands', capital: 'King Edward Point', currency: 'GBP' },
        { code: 'gy', name: 'Guyana', capital: 'Georgetown', currency: 'GYD' },
        { code: 'pe', name: 'Peru', capital: 'Lima', currency: 'PEN' },
        { code: 'py', name: 'Paraguay', capital: 'Asunción', currency: 'PYG' },
        { code: 'sr', name: 'Suriname', capital: 'Paramaribo', currency: 'SRD' },
        { code: 'uy', name: 'Uruguay', capital: 'Montevideo', currency: 'UYU' },
        { code: 've', name: 'Venezuela', capital: 'Caracas', currency: 'VES' }
    ],
    'as': [
        { code: 'ae', name: 'United Arab Emirates', capital: 'Abu Dhabi', currency: 'AED' },
        { code: 'af', name: 'Afghanistan', capital: 'Kabul', currency: 'AFN' },
        { code: 'am', name: 'Armenia', capital: 'Yerevan', currency: 'AMD' },
        { code: 'az', name: 'Azerbaijan', capital: 'Baku', currency: 'AZN' },
        { code: 'bd', name: 'Bangladesh', capital: 'Dhaka', currency: 'BDT' },
        { code: 'bh', name: 'Bahrain', capital: 'Manama', currency: 'BHD' },
        { code: 'bn', name: 'Brunei Darussalam', capital: 'Bandar Seri Begawan', currency: 'BND' },
        { code: 'bt', name: 'Bhutan', capital: 'Thimphu', currency: 'BTN' },
        { code: 'cc', name: 'Cocos (Keeling) Islands', capital: 'West Island', currency: 'AUD' },
        { code: 'cn', name: 'China', capital: 'Beijing', currency: 'CNY' },
        { code: 'cx', name: 'Christmas Island', capital: 'Flying Fish Cove', currency: 'AUD' },
        { code: 'cy', name: 'Cyprus', capital: 'Nicosia', currency: 'EUR' },
        { code: 'ge', name: 'Georgia', capital: 'Tbilisi', currency: 'GEL' },
        { code: 'hk', name: 'Hong Kong', capital: 'Hong Kong', currency: 'HKD' },
        { code: 'id', name: 'Indonesia', capital: 'Jakarta', currency: 'IDR' },
        { code: 'il', name: 'Israel', capital: 'Jerusalem', currency: 'ILS' },
        { code: 'in', name: 'India', capital: 'New Delhi', currency: 'INR' },
        { code: 'io', name: 'British Indian Ocean Territory', capital: 'Diego Garcia', currency: 'USD' },
        { code: 'iq', name: 'Iraq', capital: 'Baghdad', currency: 'IQD' },
        { code: 'ir', name: 'Iran', capital: 'Tehran', currency: 'IRR' },
        { code: 'jo', name: 'Jordan', capital: 'Amman', currency: 'JOD' },
        { code: 'jp', name: 'Japan', capital: 'Tokyo', currency: 'JPY' },
        { code: 'kg', name: 'Kyrgyzstan', capital: 'Bishkek', currency: 'KGS' },
        { code: 'kh', name: 'Cambodia', capital: 'Phnom Penh', currency: 'KHR' },
        { code: 'kp', name: 'North Korea', capital: 'Pyongyang', currency: 'KPW' },
        { code: 'kr', name: 'South Korea', capital: 'Seoul', currency: 'KRW' },
        { code: 'kw', name: 'Kuwait', capital: 'Kuwait City', currency: 'KWD' },
        { code: 'kz', name: 'Kazakhstan', capital: 'Nur-Sultan', currency: 'KZT' },
        { code: 'la', name: 'Laos', capital: 'Vientiane', currency: 'LAK' },
        { code: 'lb', name: 'Lebanon', capital: 'Beirut', currency: 'LBP' },
        { code: 'lk', name: 'Sri Lanka', capital: 'Colombo', currency: 'LKR' },
        { code: 'mm', name: 'Myanmar', capital: 'Naypyidaw', currency: 'MMK' },
        { code: 'mn', name: 'Mongolia', capital: 'Ulaanbaatar', currency: 'MNT' },
        { code: 'mo', name: 'Macau', capital: 'Macau', currency: 'MOP' },
        { code: 'mv', name: 'Maldives', capital: 'Malé', currency: 'MVR' },
        { code: 'my', name: 'Malaysia', capital: 'Kuala Lumpur', currency: 'MYR' },
        { code: 'np', name: 'Nepal', capital: 'Kathmandu', currency: 'NPR' },
        { code: 'om', name: 'Oman', capital: 'Muscat', currency: 'OMR' },
        { code: 'ph', name: 'Philippines', capital: 'Manila', currency: 'PHP' },
        { code: 'pk', name: 'Pakistan', capital: 'Islamabad', currency: 'PKR' },
        { code: 'ps', name: 'State of Palestine', capital: 'Ramallah', currency: 'ILS' },
        { code: 'qa', name: 'Qatar', capital: 'Doha', currency: 'QAR' },
        { code: 'ru', name: 'Russia', capital: 'Moscow', currency: 'RUB' },
        { code: 'sa', name: 'Saudi Arabia', capital: 'Riyadh', currency: 'SAR' },
        { code: 'sg', name: 'Singapore', capital: 'Singapore', currency: 'SGD' },
        { code: 'sy', name: 'Syria', capital: 'Damascus', currency: 'SYP' },
        { code: 'th', name: 'Thailand', capital: 'Bangkok', currency: 'THB' },
        { code: 'tj', name: 'Tajikistan', capital: 'Dushanbe', currency: 'TJS' },
        { code: 'tl', name: 'Timor-Leste', capital: 'Dili', currency: 'USD' },
        { code: 'tm', name: 'Turkmenistan', capital: 'Ashgabat', currency: 'TMT' },
        { code: 'tr', name: 'Türkiye', capital: 'Ankara', currency: 'TRY' },
        { code: 'tw', name: 'Taiwan', capital: 'Taipei', currency: 'TWD' },
        { code: 'uz', name: 'Uzbekistan', capital: 'Tashkent', currency: 'UZS' },
        { code: 'vn', name: 'Vietnam', capital: 'Hanoi', currency: 'VND' },
        { code: 'ye', name: 'Yemen', capital: 'Sana\'a', currency: 'YER' }
    ],
    'af': [
        { code: 'ao', name: 'Angola', capital: 'Luanda', currency: 'AOA' },
        { code: 'bf', name: 'Burkina Faso', capital: 'Ouagadougou', currency: 'XOF' },
        { code: 'bi', name: 'Burundi', capital: 'Gitega', currency: 'BIF' },
        { code: 'bj', name: 'Benin', capital: 'Porto-Novo', currency: 'XOF' },
        { code: 'bw', name: 'Botswana', capital: 'Gaborone', currency: 'BWP' },
        { code: 'cd', name: 'Democratic Republic of the Congo', capital: 'Kinshasa', currency: 'CDF' },
        { code: 'cf', name: 'Central African Republic', capital: 'Bangui', currency: 'XAF' },
        { code: 'cg', name: 'Republic of the Congo', capital: 'Brazzaville', currency: 'XAF' },
        { code: 'ci', name: 'Côte d\'Ivoire', capital: 'Yamoussoukro', currency: 'XOF' },
        { code: 'cm', name: 'Cameroon', capital: 'Yaoundé', currency: 'XAF' },
        { code: 'cv', name: 'Cabo Verde', capital: 'Praia', currency: 'CVE' },
        { code: 'dj', name: 'Djibouti', capital: 'Djibouti City', currency: 'DJF' },
        { code: 'dz', name: 'Algeria', capital: 'Algiers', currency: 'DZD' },
        { code: 'eg', name: 'Egypt', capital: 'Cairo', currency: 'EGP' },
        { code: 'eh', name: 'Western Sahara', capital: 'El Aaiún', currency: 'MAD' },
        { code: 'er', name: 'Eritrea', capital: 'Asmara', currency: 'ERN' },
        { code: 'et', name: 'Ethiopia', capital: 'Addis Ababa', currency: 'ETB' },
        { code: 'ga', name: 'Gabon', capital: 'Libreville', currency: 'XAF' },
        { code: 'gh', name: 'Ghana', capital: 'Accra', currency: 'GHS' },
        { code: 'gm', name: 'Gambia', capital: 'Banjul', currency: 'GMD' },
        { code: 'gn', name: 'Guinea', capital: 'Conakry', currency: 'GNF' },
        { code: 'gw', name: 'Guinea-Bissau', capital: 'Bissau', currency: 'XOF' },
        { code: 'ke', name: 'Kenya', capital: 'Nairobi', currency: 'KES' },
        { code: 'km', name: 'Comoros', capital: 'Moroni', currency: 'KMF' },
        { code: 'lr', name: 'Liberia', capital: 'Monrovia', currency: 'LRD' },
        { code: 'ls', name: 'Lesotho', capital: 'Maseru', currency: 'LSL' },
        { code: 'ly', name: 'Libya', capital: 'Tripoli', currency: 'LYD' },
        { code: 'ma', name: 'Morocco', capital: 'Rabat', currency: 'MAD' },
        { code: 'mg', name: 'Madagascar', capital: 'Antananarivo', currency: 'MGA' },
        { code: 'ml', name: 'Mali', capital: 'Bamako', currency: 'XOF' },
        { code: 'mr', name: 'Mauritania', capital: 'Nouakchott', currency: 'MRU' },
        { code: 'mu', name: 'Mauritius', capital: 'Port Louis', currency: 'MUR' },
        { code: 'mw', name: 'Malawi', capital: 'Lilongwe', currency: 'MWK' },
        { code: 'mz', name: 'Mozambique', capital: 'Maputo', currency: 'MZN' },
        { code: 'na', name: 'Namibia', capital: 'Windhoek', currency: 'NAD' },
        { code: 'ne', name: 'Niger', capital: 'Niamey', currency: 'XOF' },
        { code: 'ng', name: 'Nigeria', capital: 'Abuja', currency: 'NGN' },
        { code: 're', name: 'Réunion', capital: 'Saint-Denis', currency: 'EUR' },
        { code: 'rw', name: 'Rwanda', capital: 'Kigali', currency: 'RWF' },
        { code: 'sc', name: 'Seychelles', capital: 'Victoria', currency: 'SCR' },
        { code: 'sd', name: 'Sudan', capital: 'Khartoum', currency: 'SDG' },
        { code: 'sh', name: 'Saint Helena, Ascension and Tristan da Cunha', capital: 'Jamestown', currency: 'SHP' },
        { code: 'sl', name: 'Sierra Leone', capital: 'Freetown', currency: 'SLE' },
        { code: 'sn', name: 'Senegal', capital: 'Dakar', currency: 'XOF' },
        { code: 'so', name: 'Somalia', capital: 'Mogadishu', currency: 'SOS' },
        { code: 'ss', name: 'South Sudan', capital: 'Juba', currency: 'SSP' },
        { code: 'st', name: 'Sao Tome and Principe', capital: 'São Tomé', currency: 'STN' },
        { code: 'sz', name: 'Eswatini', capital: 'Mbabane', currency: 'SZL' },
        { code: 'td', name: 'Chad', capital: 'N\'Djamena', currency: 'XAF' },
        { code: 'tg', name: 'Togo', capital: 'Lomé', currency: 'XOF' },
        { code: 'tn', name: 'Tunisia', capital: 'Tunis', currency: 'TND' },
        { code: 'tz', name: 'Tanzania', capital: 'Dodoma', currency: 'TZS' },
        { code: 'ug', name: 'Uganda', capital: 'Kampala', currency: 'UGX' },
        { code: 'yt', name: 'Mayotte', capital: 'Mamoudzou', currency: 'EUR' },
        { code: 'za', name: 'South Africa', capital: 'Cape Town', currency: 'ZAR' },
        { code: 'zm', name: 'Zambia', capital: 'Lusaka', currency: 'ZMW' },
        { code: 'zw', name: 'Zimbabwe', capital: 'Harare', currency: 'USD' }
    ],
    'oc': [
        { code: 'as', name: 'American Samoa', capital: 'Pago Pago', currency: 'USD' },
        { code: 'au', name: 'Australia', capital: 'Canberra', currency: 'AUD' },
        { code: 'ck', name: 'Cook Islands', capital: 'Avarua', currency: 'NZD' },
        { code: 'fj', name: 'Fiji', capital: 'Suva', currency: 'FJD' },
        { code: 'fm', name: 'Federated States of Micronesia', capital: 'Palikir', currency: 'USD' },
        { code: 'gu', name: 'Guam', capital: 'Hagåtña', currency: 'USD' },
        { code: 'ki', name: 'Kiribati', capital: 'South Tarawa', currency: 'AUD' },
        { code: 'mh', name: 'Marshall Islands', capital: 'Majuro', currency: 'USD' },
        { code: 'mp', name: 'Northern Mariana Islands', capital: 'Saipan', currency: 'USD' },
        { code: 'nc', name: 'New Caledonia', capital: 'Nouméa', currency: 'XPF' },
        { code: 'nf', name: 'Norfolk Island', capital: 'Kingston', currency: 'AUD' },
        { code: 'nr', name: 'Nauru', capital: 'Yaren', currency: 'AUD' },
        { code: 'nu', name: 'Niue', capital: 'Alofi', currency: 'NZD' },
        { code: 'nz', name: 'New Zealand', capital: 'Wellington', currency: 'NZD' },
        { code: 'pf', name: 'French Polynesia', capital: 'Papeete', currency: 'XPF' },
        { code: 'pg', name: 'Papua New Guinea', capital: 'Port Moresby', currency: 'PGK' },
        { code: 'pn', name: 'Pitcairn', capital: 'Adamstown', currency: 'NZD' },
        { code: 'pw', name: 'Palau', capital: 'Ngerulmud', currency: 'USD' },
        { code: 'sb', name: 'Solomon Islands', capital: 'Honiara', currency: 'SBD' },
        { code: 'tk', name: 'Tokelau', capital: 'Atafu', currency: 'NZD' },
        { code: 'to', name: 'Tonga', capital: 'Nuku\'alofa', currency: 'TOP' },
        { code: 'tv', name: 'Tuvalu', capital: 'Funafuti', currency: 'AUD' },
        { code: 'um', name: 'United States Minor Outlying Islands', capital: 'None', currency: 'USD' },
        { code: 'vu', name: 'Vanuatu', capital: 'Port Vila', currency: 'VUV' },
        { code: 'wf', name: 'Wallis and Futuna', capital: 'Mata-Utu', currency: 'XPF' },
        { code: 'ws', name: 'Samoa', capital: 'Apia', currency: 'WST' }
    ],
    // Additional territories and special regions
    'territories': [
        { code: 'aq', name: 'Antarctica', capital: 'None', currency: 'None' },
        { code: 'ax', name: 'Aland Islands', capital: 'Mariehamn', currency: 'EUR' },
        { code: 'bv', name: 'Bouvet Island', capital: 'None', currency: 'NOK' },
        { code: 'cp', name: 'Clipperton Island', capital: 'None', currency: 'EUR' },
        { code: 'dg', name: 'Diego Garcia', capital: 'Diego Garcia', currency: 'USD' },
        { code: 'hm', name: 'Heard Island and McDonald Islands', capital: 'None', currency: 'AUD' },
        { code: 'tf', name: 'French Southern Territories', capital: 'Port-aux-Français', currency: 'EUR' }
    ]
};

// Function to get countries by region
function getCountriesByRegion(region) {
    if (region === 'wrld') {
        // Combine all regions for world mode (excluding territories by default)
        return Object.entries(CountryData)
            .filter(([key]) => key !== 'territories')
            .map(([_, countries]) => countries)
            .flat();
    }
    
    return CountryData[region] || [];
}

// Function to get all countries including territories
function getAllCountriesAndTerritories() {
    return Object.values(CountryData).flat();
}

// Export for use in other files (if using modules)
// If not using modules, the functions will be available globally
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { CountryData, getCountriesByRegion, getAllCountriesAndTerritories };
}
